Responsive2
WildCodeSchool/2022-03-JS-Lille-project-3-g3-stAmandHandBall pull request #107
Opened 2022-07-25 12:22 UTC by NtGZeko

2022-07-25 14:10 UTC, FrancoisSalmon approved these changes
ok for me

2022-07-25 14:16 UTC, LuigiMenez requested changes
Dead code

2022-07-25 14:16 UTC, LuigiMenez commented on frontend/src/components/TextPhilosophy/style.jsx
> +  /*
Dead code

2022-07-25 14:16 UTC, LuigiMenez commented on frontend/src/components/TextPhilosophy/style.jsx
> +    /*
Same

2022-07-25 18:03 UTC, FrancoisSalmon approved these changes
ok for me

2022-07-26 08:03 UTC, LuigiMenez approved these changes
Ok for me

2022-07-26 09:32 UTC, LoicBrassart approved these changes
SnE

2022-07-26 09:37 UTC, merged