add timeline, card event  and history page
WildCodeSchool/2022-03-JS-Lille-project-3-g3-stAmandHandBall pull request #13
Opened 2022-06-07 15:07 UTC by Hamza-Luciano

2022-06-07 15:08 UTC, FrancoisSalmon submitted a review, later dismissed
ok for me

2022-06-07 22:39 UTC, LuigiMenez requested changes
Why the <i> HTML element???

2022-06-07 22:39 UTC, LuigiMenez commented on frontend/src/components/CardEvent/index.jsx
> +          <i className="icon fa fa-home" />
???

2022-06-08 09:12 UTC, FrancoisSalmon approved these changes
ok

2022-06-08 14:42 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-09 00:28 UTC, LoicBrassart approved these changes
sne

2022-06-09 06:00 UTC, merged