finalization of the integration
WildCodeSchool/2022-03-JS-Lille-project-3-g3-stAmandHandBall pull request #14
Opened 2022-06-08 09:40 UTC by RomainLF

2022-06-08 10:45 UTC, FrancoisSalmon requested changes
try to do this without z-index

2022-06-08 10:45 UTC, FrancoisSalmon commented on frontend/src/components/Networks/style.jsx
> +      z-index: 1;
try to do this without z-index

2022-06-08 15:26 UTC, LuigiMenez requested changes
Use import absolute

2022-06-08 15:26 UTC, LuigiMenez commented on frontend/src/components/Networks/index.jsx
> +import imgNetworks from "../../assets/imgNetworks.jpg";
Use import absolue

2022-06-09 07:59 UTC, FrancoisSalmon approved these changes
ok

2022-06-09 08:16 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-09 09:19 UTC, FrancoisSalmon approved these changes
conflicts resolved

2022-06-09 10:28 UTC, LoicBrassart approved these changes
SnE

2022-06-09 10:31 UTC, merged