Creation page calendar, card calendar, add route
WildCodeSchool/2022-03-JS-Lille-project-3-g3-stAmandHandBall pull request #16
Opened 2022-06-08 13:05 UTC by Gonaline

2022-06-08 13:51 UTC, Hamza-Luciano approved these changes

2022-06-08 15:07 UTC, LuigiMenez requested changes
Use import absolute & dead code

2022-06-08 15:07 UTC, LuigiMenez commented on frontend/src/components/CardCalendar/index.jsx
> +import domicile from "../../assets/Pictures/cards/calendar/picto-maison.png";
Use import absolute

2022-06-08 15:07 UTC, LuigiMenez commented on frontend/src/components/CardCalendar/style.jsx
> +    /* text-shadow: 2px 2px 5px black;
No Dead code

2022-06-09 05:39 UTC, Gonaline commented on frontend/src/components/CardCalendar/index.jsx
> +import domicile from "../../assets/Pictures/cards/calendar/picto-maison.png";
ok

2022-06-09 05:39 UTC, Gonaline commented on frontend/src/components/CardCalendar/style.jsx
> +    /* text-shadow: 2px 2px 5px black;
ok

2022-06-09 06:03 UTC, FrancoisSalmon approved these changes
no more dead code and absolute import ok

2022-06-09 08:04 UTC, LuigiMenez requested changes
Fix conflict

2022-06-09 09:13 UTC, FrancoisSalmon approved these changes
conflicts resolved

2022-06-09 10:01 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-09 10:43 UTC, LoicBrassart approved these changes
SnE

2022-06-09 10:50 UTC, merged