add shop banniere
WildCodeSchool/2022-03-JS-Lille-project-3-g3-stAmandHandBall pull request #20
Opened 2022-06-09 14:33 UTC by RomainLF

2022-06-09 14:40 UTC, FrancoisSalmon approved these changes
ok

2022-06-09 15:26 UTC, LuigiMenez requested changes
Dead code

2022-06-09 15:26 UTC, LuigiMenez commented on frontend/src/components/BanShop/style.jsx
> +    //background-color: red;
Dead Code

2022-06-10 06:37 UTC, FrancoisSalmon approved these changes
ok for me

2022-06-10 06:50 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-10 07:36 UTC, LoicBrassart approved these changes
SnE

2022-06-10 11:23 UTC, merged