Fix link
WildCodeSchool/2022-03-JS-Lille-project-3-g3-stAmandHandBall pull request #28
Opened 2022-06-14 12:38 UTC by NtGZeko

2022-06-14 15:07 UTC, FrancoisSalmon approved these changes
ok for me

2022-06-15 09:31 UTC, FrancoisSalmon submitted a review, later dismissed
conflicts fix ok for me

2022-06-15 13:17 UTC, LuigiMenez submitted a review, later dismissed
Ok for me

2022-06-16 08:03 UTC, LoicBrassart requested changes
Won't read, big refactoring to do :(

2022-06-16 08:03 UTC, LoicBrassart commented on frontend/src/App.jsx
> +import Partenaire from "@pages/Partenaire";
Name your components in English

2022-06-16 19:48 UTC, FrancoisSalmon submitted a review, later dismissed
no more french, ok for me

2022-06-17 10:00 UTC, LuigiMenez requested changes
Warning name styled components

2022-06-17 10:37 UTC, FrancoisSalmon requested changes
still french in partner pages

2022-06-17 10:37 UTC, FrancoisSalmon commented on frontend/src/pages/Partner/index.jsx
> +    <SPartenaire>
still in french

2022-06-17 12:40 UTC, FrancoisSalmon submitted a review, later dismissed
the final i hope

2022-06-17 15:27 UTC, LuigiMenez requested changes
Fix conflict

2022-06-20 09:42 UTC, FrancoisSalmon submitted a review, later dismissed
ok

2022-06-20 10:21 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-20 10:47 UTC, LoicBrassart requested changes
Please fix these

2022-06-20 10:47 UTC, LoicBrassart commented on frontend/src/components/Archi/Footer/index.jsx
> +
Why add an empty line ? You edited this on GHub, didn't you ?

2022-06-20 10:47 UTC, LoicBrassart commented on frontend/src/components/Archi/Header/index.jsx
> +import Navbar from "../Navbar";
Use aliases

2022-06-20 12:13 UTC, FrancoisSalmon approved these changes
corrections ok

2022-06-20 13:38 UTC, LuigiMenez approved these changes
Ok for me

2022-06-20 15:45 UTC, LoicBrassart approved these changes
NmE! <3

2022-06-21 06:41 UTC, merged