003 header
WildCodeSchool/2022-03-JS-Lille-project-3-g3-stAmandHandBall pull request #3
Opened 2022-06-02 10:01 UTC by FrancoisSalmon

2022-06-02 10:06 UTC, Gonaline submitted a review, later dismissed
ok

2022-06-02 10:39 UTC, LuigiMenez requested changes
Learn how to use a z-index

2022-06-02 10:39 UTC, LuigiMenez commented on frontend/src/components/Archi/Header/style.jsx
> +    z-index: 1;
Learn how to use a z-index

2022-06-02 10:39 UTC, LuigiMenez commented on frontend/src/components/Archi/Header/style.jsx
> +      z-index: 1;
Learn how to use a z-index

2022-06-03 13:56 UTC, Gonaline submitted a review, later dismissed
ok

2022-06-07 07:24 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-07 07:25 UTC, LuigiMenez requested changes
Fix conflict

2022-06-07 11:22 UTC, Gonaline approved these changes
ok

2022-06-07 13:40 UTC, LuigiMenez approved these changes
Ok for me

2022-06-07 14:01 UTC, merged