Block photos link
WildCodeSchool/2022-03-JS-Lille-project-3-g3-stAmandHandBall pull request #36
Opened 2022-06-15 12:58 UTC by NtGZeko

2022-06-15 14:41 UTC, FrancoisSalmon approved these changes
ok for me

2022-06-16 09:50 UTC, LuigiMenez requested changes
Why a big space?

2022-06-16 09:50 UTC, LuigiMenez commented on frontend/src/components/BlocCf/index.jsx
> +        <div className="photoDiv 	fifthPhoto">
Why a big space?

2022-06-17 09:14 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-17 09:36 UTC, LoicBrassart approved these changes
SnE

2022-06-17 09:54 UTC, merged