add responsive version
WildCodeSchool/2022-03-JS-Lille-project-3-g3-stAmandHandBall pull request #44
Opened 2022-06-21 09:40 UTC by Gonaline

2022-06-21 09:51 UTC, FrancoisSalmon approved these changes
ok

2022-06-21 09:56 UTC, LuigiMenez approved these changes
Ok for me

2022-06-22 10:29 UTC, LoicBrassart requested changes
Fix the call to your assets

2022-06-22 10:29 UTC, LoicBrassart commented on frontend/src/components/CardCalendar/index.jsx
> +          src={`../../src/assets/images/logos/${hit}.png`}
Use `@assets`

2022-06-23 13:43 UTC, LoicBrassart approved these changes

2022-06-23 14:17 UTC, merged