Back test
WildCodeSchool/2022-03-JS-Lille-project-3-g3-stAmandHandBall pull request #45
Opened 2022-06-21 15:05 UTC by Gonaline

2022-06-21 15:16 UTC, FrancoisSalmon submitted a review, later dismissed
ok for me

2022-06-22 08:51 UTC, LuigiMenez approved these changes
I have not been able to see two files to ensure that they are not corrupted

2022-06-22 08:51 UTC, LuigiMenez commented on frontend/src/services/context/Ctx.jsx
> +    axios.get("http://localhost:5000/players").then(({ data }) => {
Use environement variable for call of axios

2022-06-22 08:54 UTC, LuigiMenez requested changes
use variable environement, I have not been able to see two files to ensure that they are not corrupted

2022-06-22 12:06 UTC, FrancoisSalmon approved these changes
ok

2022-06-23 07:18 UTC, LuigiMenez approved these changes
Ok, be careful with the branch name, not very clear

2022-06-23 14:17 UTC, merged