019 form 2.0
WildCodeSchool/2022-03-JS-Lille-project-3-g3-stAmandHandBall pull request #53
Opened 2022-06-23 12:53 UTC by Hamza-Luciano

2022-06-23 14:36 UTC, FrancoisSalmon approved these changes
Clean old import

2022-06-24 07:10 UTC, LuigiMenez approved these changes
Ok

2022-06-24 07:10 UTC, LuigiMenez commented on frontend/src/components/Form/index.jsx
>        <form action="">
Why is the action empty?

2022-06-24 07:29 UTC, LoicBrassart requested changes
- Answer Luigi's question
- Your commit messages don't tell anything useful
- You must code the backend along with your frontend

2022-06-24 07:29 UTC, LoicBrassart commented on frontend/src/components/Form/index.jsx
> +  const [email, setEmail] = useState("");
We saw how to create one state to store all field's information, to make the next steps easier

2022-07-07 09:21 UTC, closed without merging