Route
WildCodeSchool/2022-03-JS-Lille-project-3-g3-stAmandHandBall pull request #61
Opened 2022-06-24 12:33 UTC by NtGZeko

2022-06-24 13:46 UTC, NtGZeko commented
fixed from github

2022-06-24 15:24 UTC, FrancoisSalmon submitted a review, later dismissed
ok

2022-06-27 06:52 UTC, LuigiMenez requested changes
Routes useless

2022-06-27 06:52 UTC, LuigiMenez commented on backend/src/router.js
> +router.get("/staffs/:id", StaffController.browse);
Useless

2022-06-27 06:52 UTC, LuigiMenez commented on backend/src/router.js
> +router.get("/items/:id", ItemController.browse);
Useless

2022-06-28 10:07 UTC, FrancoisSalmon approved these changes
ok

2022-07-01 13:11 UTC, LoicBrassart approved these changes
SnE

2022-07-04 06:50 UTC, merged