Rookies
WildCodeSchool/2022-03-JS-Lille-project-3-g3-stAmandHandBall pull request #72
Opened 2022-07-05 12:09 UTC by Gonaline

2022-07-05 12:18 UTC, RomainLF approved these changes

2022-07-05 12:18 UTC, RomainLF commented
ok for me

2022-07-06 07:46 UTC, LuigiMenez approved these changes
Ok for me.

2022-07-06 14:15 UTC, LoicBrassart requested changes

2022-07-06 14:15 UTC, LoicBrassart commented on frontend/src/services/context/Ctx.jsx
> +        setTeam(data).then(() => {});
Remve the empty `.then`

2022-07-07 08:10 UTC, FrancoisSalmon commented
supress PR replace by create pages nonProfessional & detail

2022-07-07 08:10 UTC, closed without merging