add page CF Philosophy
WildCodeSchool/2022-03-JS-Lille-project-3-g3-stAmandHandBall pull request #76
Opened 2022-07-06 10:20 UTC by Hamza-Luciano

2022-07-06 14:54 UTC, FrancoisSalmon submitted a review, later dismissed
ok

2022-07-07 07:10 UTC, LuigiMenez requested changes
Fix minor

2022-07-07 07:10 UTC, LuigiMenez commented on frontend/src/components/TextPhilosophy/index.jsx
> +        <div className="descriptifText">
In english please "descriptiveText"

2022-07-07 07:10 UTC, LuigiMenez commented on frontend/src/components/TextPhilosophy/index.jsx
> +        <div className="descriptifText">
same

2022-07-07 07:10 UTC, LuigiMenez commented on frontend/src/components/TextPhilosophy/index.jsx
> +        <div className="descriptifText">
Same

2022-07-07 10:26 UTC, FrancoisSalmon approved these changes
ok for me

2022-07-11 08:11 UTC, LoicBrassart approved these changes
SnE

2022-07-11 08:12 UTC, merged