creation contact form, setup route to back end, creation contact DB t…
WildCodeSchool/2022-03-JS-Lille-project-3-g3-stAmandHandBall pull request #82
Opened 2022-07-07 09:48 UTC by FrancoisSalmon

…o receive message, add and configure toastify

2022-07-07 10:24 UTC, Gonaline submitted a review, later dismissed
ok

2022-07-07 14:35 UTC, LuigiMenez submitted a review, later dismissed
Ok for me.

2022-07-11 08:37 UTC, Gonaline approved these changes
ok

2022-07-11 08:56 UTC, LuigiMenez approved these changes
Ok for me.

2022-07-11 13:56 UTC, LoicBrassart commented
Conflicts still

2022-07-11 14:14 UTC, LuigiMenez requested changes
Fix conflict

2022-07-11 14:22 UTC, LoicBrassart commented
Conflicts + Plz stop asigning me, Luigi is in charge of the 2nd review

2022-07-11 14:27 UTC, Gonaline submitted a review, later dismissed
ok

2022-07-12 06:39 UTC, LuigiMenez requested changes
Line blank useless

2022-07-12 06:39 UTC, LuigiMenez commented on frontend/src/services/context/Ctx.jsx
> +
Line Blank useless

2022-07-12 06:39 UTC, LuigiMenez commented on backend/src/router.js
> +
Line blank useless

2022-07-13 08:13 UTC, Gonaline approved these changes
ok

2022-07-13 09:55 UTC, LuigiMenez approved these changes
Ok for me.

2022-07-13 13:44 UTC, LoicBrassart approved these changes
SnE, one typo to fix

2022-07-13 13:44 UTC, LoicBrassart commented on frontend/src/components/Form/index.jsx
> +          "Un problème est survenue, merci de réessayer ultérieurement "
"survenu"

2022-07-13 14:03 UTC, merged