Coach page
WildCodeSchool/2022-03-JS-Lille-project-3-g3-stAmandHandBall pull request #95
Opened 2022-07-13 14:22 UTC by NtGZeko

2022-07-18 05:25 UTC, FrancoisSalmon submitted a review, later dismissed

2022-07-18 07:53 UTC, LuigiMenez requested changes
Query indentation to be reviewed.

2022-07-18 07:53 UTC, LuigiMenez commented on backend/src/models/TeamAndStaffManager.js
> +      `SELECT *
This could be a nicer indentation.

2022-07-18 08:13 UTC, FrancoisSalmon approved these changes
ok

2022-07-18 08:17 UTC, LuigiMenez approved these changes
Ok for me.

2022-07-18 09:50 UTC, LoicBrassart submitted a review, later dismissed
SnE

2022-07-19 07:25 UTC, LuigiMenez approved these changes
Ok for me.

2022-07-22 08:20 UTC, LoicBrassart approved these changes
SnE

2022-07-22 13:03 UTC, merged